// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: 1111

#ifndef _1111_UI_H
#define _1111_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_AlarmLabel;
extern lv_obj_t * ui_HumiLabel;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_pico2_photos_1_png);    // assets/pico2_photos_1.png
LV_IMG_DECLARE(ui_img_761490535);    // assets/pico2_photos-02.png
LV_IMG_DECLARE(ui_img_673885694);    // assets/pico2_photos-03.png
LV_IMG_DECLARE(ui_img_1083188165);    // assets/pico2_photos-04.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
