// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: 1111

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image1, &ui_img_pico2_photos_1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image2, &ui_img_761490535);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 56
    lv_obj_set_x(ui_Image2, -100);
    lv_obj_set_y(ui_Image2, -80);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image3, &ui_img_673885694);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 56
    lv_obj_set_x(ui_Image3, -100);
    lv_obj_set_y(ui_Image3, 80);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image4, &ui_img_1083188165);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 56
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 56
    lv_obj_set_x(ui_Image4, -100);
    lv_obj_set_y(ui_Image4, 0);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 0);
    lv_obj_set_y(ui_TempLabel, -80);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "26");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0x5ABEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_AlarmLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmLabel, 36);
    lv_obj_set_y(ui_AlarmLabel, 0);
    lv_obj_set_align(ui_AlarmLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmLabel, "Temperature is high");
    lv_obj_set_style_text_color(ui_AlarmLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel, 0);
    lv_obj_set_y(ui_HumiLabel, 80);
    lv_obj_set_align(ui_HumiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel, "50");
    lv_obj_set_style_text_color(ui_HumiLabel, lv_color_hex(0xCD5D75), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HumiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HumiLabel, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 71);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 109);
    lv_obj_set_y(ui_Button1, 84);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x51BD98), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "LED");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}
