// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: 1111

#include "ui.h"
#include <Arduino.h> 

void LED_Control(lv_event_t * e)
{
	// Your code here
  // Get the current LED status and switch
  static bool ledState = false;
  ledState = !ledState;
  
  // Set green light status
  digitalWrite(19, ledState ? HIGH : LOW);
}
